version: '3'
services:
  server:
    build: 'server'
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    build: 'postgres'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password